import type { Metadata } from "next";
import { Geist,  } from "@/src/constants/font";
import "./globals.css";
import Footer from "@/src/components/module/Fotter"
import Navbar from "@/src/components/module/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Geist.className} antialiased  `}>
        <Navbar />
        <div className="min-h-[80vh] pt-16">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
